"""
chat/encryption.py
------------------
Fernet-based symmetric encryption for chat message text.

All message text is encrypted before being written to MongoDB and
decrypted transparently when serialised back to the client. The
encryption key is stored in the CHAT_ENCRYPTION_KEY environment
variable (a URL-safe base64-encoded 32-byte key generated by Fernet).

Key generation (run once, store output in .env):
    python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
"""

import os
import mongoengine as me
from cryptography.fernet import Fernet, InvalidToken

import logging

logger = logging.getLogger(__name__)

_fernet: Fernet | None = None
_fernet_init_error: str | None = None  # set once if key is bad/missing


def _get_fernet() -> Fernet | None:
    """Return the singleton Fernet instance, or None if the key is unavailable."""
    global _fernet, _fernet_init_error
    if _fernet is not None:
        return _fernet
    if _fernet_init_error is not None:
        return None  # already tried and failed

    raw_key = os.getenv("CHAT_ENCRYPTION_KEY", "").strip()
    if not raw_key:
        _fernet_init_error = "CHAT_ENCRYPTION_KEY is not set"
        logger.warning(
            "[chat.encryption] CHAT_ENCRYPTION_KEY is not set — "
            "messages will be stored as plaintext and existing enc: entries "
            "will show a placeholder. Set the key to match production."
        )
        return None

    try:
        _fernet = Fernet(raw_key.encode())
        return _fernet
    except Exception as exc:
        _fernet_init_error = str(exc)
        logger.warning(
            "[chat.encryption] CHAT_ENCRYPTION_KEY is invalid (%s) — "
            "falling back to no-op mode.", exc
        )
        return None


_CIPHER_PREFIX = "enc:"


def encrypt_text(plaintext: str) -> str:
    """
    Encrypt plaintext and return a prefixed ciphertext string safe for
    storage in MongoDB. Returns the original string unchanged if it is
    already encrypted or if the encryption key is unavailable.
    """
    if not plaintext:
        return plaintext
    if plaintext.startswith(_CIPHER_PREFIX):
        return plaintext  # already encrypted — idempotent
    f = _get_fernet()
    if f is None:
        return plaintext  # no-op: key unavailable, store as plaintext
    token = f.encrypt(plaintext.encode("utf-8"))
    return _CIPHER_PREFIX + token.decode("ascii")


def decrypt_text(ciphertext: str) -> str:
    """
    Decrypt a previously encrypted string. If the value does not have
    the expected prefix it is assumed to be legacy plaintext and
    returned as-is. Returns a readable placeholder if the key is
    unavailable or the token is invalid.
    """
    if not ciphertext:
        return ciphertext
    if not ciphertext.startswith(_CIPHER_PREFIX):
        return ciphertext  # legacy plaintext — return unchanged

    f = _get_fernet()
    if f is None:
        # Key unavailable locally — return placeholder instead of raw ciphertext
        return "[message encrypted — key not configured locally]"

    token = ciphertext[len(_CIPHER_PREFIX):]
    try:
        return f.decrypt(token.encode("ascii")).decode("utf-8")
    except (InvalidToken, Exception):
        return "[encrypted message — unable to decrypt]"


class EncryptedStringField(me.StringField):
    """
    MongoEngine field that stores encrypted strings in MongoDB and
    returns plaintext to the application.
    """

    def to_mongo(self, value):
        value = super().to_mongo(value)
        if value is None:
            return None
        str_value = str(value)
        encrypted = encrypt_text(str_value)
        # Log if encryption was applied
        if encrypted.startswith(_CIPHER_PREFIX) and not str_value.startswith(_CIPHER_PREFIX):
            logger.debug(f"[ENCRYPT] encrypting {len(str_value)} chars -> {len(encrypted)} chars")
        return encrypted

    def to_python(self, value):
        value = super().to_python(value)
        if value is None:
            return None
        str_value = str(value)
        decrypted = decrypt_text(str_value)
        # Log if this is legacy plaintext (not encrypted)
        if not str_value.startswith(_CIPHER_PREFIX):
            logger.debug(f"[PLAINTEXT_LEGACY] returning plaintext message (not encrypted)")
        return decrypted
